// DEMO inventory seeds. Every item is clearly fictional and prefixed
// "DEMO:"; nothing here is a real product claim, a real price, or a real
// stock fact. The owner replaces these through the admin dashboard.
// Tracked in NEEDS-CONFIRMATION.md.

function seed(offsetDays, item) {
  const t = new Date(Date.UTC(2026, 6, 1) - offsetDays * 86400000).toISOString();
  return { createdAt: t, updatedAt: t, photos: [], featured: false, ...item };
}

export const SEED_INVENTORY = [
  seed(1, {
    id: 'demo-rifle-bolt',
    name: 'DEMO: Example Bolt-Action Rifle',
    category: 'Rifles',
    manufacturer: 'Example Arms Co.',
    model: 'Model 100',
    caliber: '.308 Win',
    condition: 'New',
    price: 649.99,
    stockStatus: 'In Stock',
    description: 'Demo listing to show how a rifle entry looks. Not a real item.',
    featured: true,
  }),
  seed(2, {
    id: 'demo-rifle-lever',
    name: 'DEMO: Example Lever-Action Rifle',
    category: 'Rifles',
    manufacturer: 'Example Arms Co.',
    model: 'Heritage 94',
    caliber: '.30-30 Win',
    condition: 'Used',
    price: 425.0,
    stockStatus: 'Low Stock',
    description: 'Demo listing for a used lever gun. Not a real item.',
  }),
  seed(3, {
    id: 'demo-handgun-compact',
    name: 'DEMO: Example Compact Pistol',
    category: 'Handguns',
    manufacturer: 'Sample Firearms',
    model: 'C-9',
    caliber: '9mm',
    condition: 'New',
    price: 389.5,
    stockStatus: 'In Stock',
    description: 'Demo listing to show how a handgun entry looks. Not a real item.',
    featured: true,
  }),
  seed(4, {
    id: 'demo-handgun-revolver',
    name: 'DEMO: Example Revolver',
    category: 'Handguns',
    manufacturer: 'Sample Firearms',
    model: 'R-38',
    caliber: '.38 Special',
    condition: 'Used',
    price: 299.0,
    stockStatus: 'Sold',
    description: 'Demo listing marked Sold so the status badge can be seen.',
  }),
  seed(5, {
    id: 'demo-shotgun-pump',
    name: 'DEMO: Example Pump Shotgun',
    category: 'Shotguns',
    manufacturer: 'Example Arms Co.',
    model: 'Field 12',
    caliber: '12 GA',
    condition: 'New',
    price: 449.0,
    stockStatus: 'In Stock',
    description: 'Demo listing to show how a shotgun entry looks. Not a real item.',
  }),
  seed(6, {
    id: 'demo-shotgun-ou',
    name: 'DEMO: Example Over-Under Shotgun',
    category: 'Shotguns',
    manufacturer: 'Sample Firearms',
    model: 'Clays 20',
    caliber: '20 GA',
    condition: 'Used',
    price: 780.0,
    stockStatus: 'Hidden',
    description: 'Demo listing marked Hidden. It never appears in public reads.',
  }),
  seed(7, {
    id: 'demo-ammo-9mm',
    name: 'DEMO: Example 9mm Range Ammo, 50 rounds',
    category: 'Ammunition',
    manufacturer: 'Sample Munitions',
    model: 'Range Pack',
    caliber: '9mm',
    condition: 'New',
    price: 17.99,
    stockStatus: 'In Stock',
    description: 'Demo listing to show how an ammunition entry looks.',
  }),
  seed(8, {
    id: 'demo-ammo-308',
    name: 'DEMO: Example .308 Hunting Ammo, 20 rounds',
    category: 'Ammunition',
    manufacturer: 'Sample Munitions',
    model: 'Field Pack',
    caliber: '.308 Win',
    condition: 'New',
    price: 32.5,
    stockStatus: 'Low Stock',
    description: 'Demo listing to show a low stock badge.',
  }),
  seed(9, {
    id: 'demo-optic-scope',
    name: 'DEMO: Example 3-9x40 Rifle Scope',
    category: 'Optics & Accessories',
    manufacturer: 'Sample Optics',
    model: 'Clearview 3940',
    caliber: '',
    condition: 'New',
    price: 159.0,
    stockStatus: 'In Stock',
    description: 'Demo listing to show how an optics entry looks.',
  }),
  seed(10, {
    id: 'demo-other-case',
    name: 'DEMO: Example Hard Rifle Case',
    category: 'Other',
    manufacturer: 'Sample Gear',
    model: 'Guard 48',
    caliber: '',
    condition: 'New',
    price: 54.99,
    stockStatus: 'In Stock',
    description: 'Demo listing in the Other category.',
  }),
];
